// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonRequestHeader.proto

package fluxapi.request;

public final class CommonRequestHeader {
  private CommonRequestHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code fluxapi.request.messageType}
   */
  public enum messageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JSON = 0;</code>
     */
    JSON(0, 0),
    /**
     * <code>XML = 1;</code>
     */
    XML(1, 1),
    /**
     * <code>PROTO = 2;</code>
     */
    PROTO(2, 2),
    ;

    /**
     * <code>JSON = 0;</code>
     */
    public static final int JSON_VALUE = 0;
    /**
     * <code>XML = 1;</code>
     */
    public static final int XML_VALUE = 1;
    /**
     * <code>PROTO = 2;</code>
     */
    public static final int PROTO_VALUE = 2;


    public final int getNumber() { return value; }

    public static messageType valueOf(int value) {
      switch (value) {
        case 0: return JSON;
        case 1: return XML;
        case 2: return PROTO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
            public messageType findValueByNumber(int number) {
              return messageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fluxapi.request.CommonRequestHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final messageType[] VALUES = values();

    public static messageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private messageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fluxapi.request.messageType)
  }

  public interface reqHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string timestamp = 1;
    /**
     * <code>required string timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    // required string identity = 2;
    /**
     * <code>required string identity = 2;</code>
     */
    boolean hasIdentity();
    /**
     * <code>required string identity = 2;</code>
     */
    java.lang.String getIdentity();
    /**
     * <code>required string identity = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdentityBytes();

    // required .fluxapi.request.messageType type = 3 [default = PROTO];
    /**
     * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
     */
    boolean hasType();
    /**
     * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
     */
    fluxapi.request.CommonRequestHeader.messageType getType();

    // required string sign = 4;
    /**
     * <code>required string sign = 4;</code>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 4;</code>
     */
    java.lang.String getSign();
    /**
     * <code>required string sign = 4;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();
  }
  /**
   * Protobuf type {@code fluxapi.request.reqHeader}
   */
  public static final class reqHeader extends
      com.google.protobuf.GeneratedMessage
      implements reqHeaderOrBuilder {
    // Use reqHeader.newBuilder() to construct.
    private reqHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private reqHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final reqHeader defaultInstance;
    public static reqHeader getDefaultInstance() {
      return defaultInstance;
    }

    public reqHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private reqHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              identity_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              fluxapi.request.CommonRequestHeader.messageType value = fluxapi.request.CommonRequestHeader.messageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              sign_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fluxapi.request.CommonRequestHeader.internal_static_fluxapi_request_reqHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fluxapi.request.CommonRequestHeader.internal_static_fluxapi_request_reqHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fluxapi.request.CommonRequestHeader.reqHeader.class, fluxapi.request.CommonRequestHeader.reqHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<reqHeader> PARSER =
        new com.google.protobuf.AbstractParser<reqHeader>() {
      public reqHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new reqHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<reqHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string timestamp = 1;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string identity = 2;
    public static final int IDENTITY_FIELD_NUMBER = 2;
    private java.lang.Object identity_;
    /**
     * <code>required string identity = 2;</code>
     */
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string identity = 2;</code>
     */
    public java.lang.String getIdentity() {
      java.lang.Object ref = identity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identity_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string identity = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityBytes() {
      java.lang.Object ref = identity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .fluxapi.request.messageType type = 3 [default = PROTO];
    public static final int TYPE_FIELD_NUMBER = 3;
    private fluxapi.request.CommonRequestHeader.messageType type_;
    /**
     * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
     */
    public fluxapi.request.CommonRequestHeader.messageType getType() {
      return type_;
    }

    // required string sign = 4;
    public static final int SIGN_FIELD_NUMBER = 4;
    private java.lang.Object sign_;
    /**
     * <code>required string sign = 4;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      timestamp_ = "";
      identity_ = "";
      type_ = fluxapi.request.CommonRequestHeader.messageType.PROTO;
      sign_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdentity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIdentityBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSignBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIdentityBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSignBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fluxapi.request.CommonRequestHeader.reqHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fluxapi.request.CommonRequestHeader.reqHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fluxapi.request.reqHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fluxapi.request.CommonRequestHeader.reqHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fluxapi.request.CommonRequestHeader.internal_static_fluxapi_request_reqHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fluxapi.request.CommonRequestHeader.internal_static_fluxapi_request_reqHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fluxapi.request.CommonRequestHeader.reqHeader.class, fluxapi.request.CommonRequestHeader.reqHeader.Builder.class);
      }

      // Construct using fluxapi.request.CommonRequestHeader.reqHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        identity_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = fluxapi.request.CommonRequestHeader.messageType.PROTO;
        bitField0_ = (bitField0_ & ~0x00000004);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fluxapi.request.CommonRequestHeader.internal_static_fluxapi_request_reqHeader_descriptor;
      }

      public fluxapi.request.CommonRequestHeader.reqHeader getDefaultInstanceForType() {
        return fluxapi.request.CommonRequestHeader.reqHeader.getDefaultInstance();
      }

      public fluxapi.request.CommonRequestHeader.reqHeader build() {
        fluxapi.request.CommonRequestHeader.reqHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fluxapi.request.CommonRequestHeader.reqHeader buildPartial() {
        fluxapi.request.CommonRequestHeader.reqHeader result = new fluxapi.request.CommonRequestHeader.reqHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identity_ = identity_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sign_ = sign_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fluxapi.request.CommonRequestHeader.reqHeader) {
          return mergeFrom((fluxapi.request.CommonRequestHeader.reqHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fluxapi.request.CommonRequestHeader.reqHeader other) {
        if (other == fluxapi.request.CommonRequestHeader.reqHeader.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000001;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasIdentity()) {
          bitField0_ |= 0x00000002;
          identity_ = other.identity_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000008;
          sign_ = other.sign_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasIdentity()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fluxapi.request.CommonRequestHeader.reqHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fluxapi.request.CommonRequestHeader.reqHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string timestamp = 1;
      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }

      // required string identity = 2;
      private java.lang.Object identity_ = "";
      /**
       * <code>required string identity = 2;</code>
       */
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string identity = 2;</code>
       */
      public java.lang.String getIdentity() {
        java.lang.Object ref = identity_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          identity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string identity = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityBytes() {
        java.lang.Object ref = identity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string identity = 2;</code>
       */
      public Builder setIdentity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string identity = 2;</code>
       */
      public Builder clearIdentity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identity_ = getDefaultInstance().getIdentity();
        onChanged();
        return this;
      }
      /**
       * <code>required string identity = 2;</code>
       */
      public Builder setIdentityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        identity_ = value;
        onChanged();
        return this;
      }

      // required .fluxapi.request.messageType type = 3 [default = PROTO];
      private fluxapi.request.CommonRequestHeader.messageType type_ = fluxapi.request.CommonRequestHeader.messageType.PROTO;
      /**
       * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
       */
      public fluxapi.request.CommonRequestHeader.messageType getType() {
        return type_;
      }
      /**
       * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
       */
      public Builder setType(fluxapi.request.CommonRequestHeader.messageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .fluxapi.request.messageType type = 3 [default = PROTO];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = fluxapi.request.CommonRequestHeader.messageType.PROTO;
        onChanged();
        return this;
      }

      // required string sign = 4;
      private java.lang.Object sign_ = "";
      /**
       * <code>required string sign = 4;</code>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string sign = 4;</code>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sign = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 4;</code>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 4;</code>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 4;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sign_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fluxapi.request.reqHeader)
    }

    static {
      defaultInstance = new reqHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fluxapi.request.reqHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fluxapi_request_reqHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fluxapi_request_reqHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031commonRequestHeader.proto\022\017fluxapi.req" +
      "uest\"q\n\treqHeader\022\021\n\ttimestamp\030\001 \002(\t\022\020\n\010" +
      "identity\030\002 \002(\t\0221\n\004type\030\003 \002(\0162\034.fluxapi.r" +
      "equest.messageType:\005PROTO\022\014\n\004sign\030\004 \002(\t*" +
      "+\n\013messageType\022\010\n\004JSON\020\000\022\007\n\003XML\020\001\022\t\n\005PRO" +
      "TO\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_fluxapi_request_reqHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_fluxapi_request_reqHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fluxapi_request_reqHeader_descriptor,
              new java.lang.String[] { "Timestamp", "Identity", "Type", "Sign", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
